# This workflow will build the IDA Pro plugin

name: Build IDA plugin

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - src/**
      - makefile
      - .github/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    env:
      SHELLOPTS: igncr
      working-directory: ida-pro-loadmap

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: ida-pro-loadmap

    - name: Check secrets
      env: 
        IDASDK_MEGA_DL: ${{ secrets.IDASDK_MEGA_DL }}
      working-directory: ${{ github.workspace }}
      if: ${{ env.IDASDK_MEGA_DL == '' }}
      # Note: This uses the bash shell included with Git on Windows.
      shell: bash
      run: |
        echo the secret \"IDASDK_MEGA_DL\" has not been made
        echo please go to \"settings \> secrets \> actions\" to create it
        exit 1

    - name: Mask the secrets
      run: |
        echo "::add-mask::${{ secrets.IDASDK_MEGA_DL }}" 

    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: wget make

    - name: Prepare for downloading from MEGA
      env:
        RUNNER_WORKSPACE: ${{ runner.workspace }}
      working-directory: ${{ github.workspace }}
      # Note: After Cygwin is installed, its bash shell is used.
      shell: bash --login --norc -eo pipefail -o igncr '{0}'
      run: |
        wget -O "${RUNNER_WORKSPACE}/MEGAcmdSetup.exe" "https://mega.nz/MEGAcmdSetup.exe"
        "${RUNNER_WORKSPACE}/MEGAcmdSetup.exe" /S
        echo "$LOCALAPPDATA/MEGAcmd" >> $GITHUB_PATH

    - name: Download IDA Pro SDK
      env:
        RUNNER_WORKSPACE: ${{ runner.workspace }}
      working-directory: ${{ github.workspace }}
      shell: bash --login --norc -eo pipefail -o igncr '{0}'
      run: |
        mega-get "https://mega.nz/file/${{ secrets.IDASDK_MEGA_DL }}" ${{ env.RUNNER_WORKSPACE }}

    - name: Create Build Environment
      env:
        RUNNER_WORKSPACE: ${{ runner.workspace }}
      working-directory: ${{ github.workspace }}
      shell: bash --login --norc -eo pipefail -o igncr '{0}'
      run: |
        7z x "-o${RUNNER_WORKSPACE}/" \
          "${RUNNER_WORKSPACE}/idasdk75.zip"
        make -C ${RUNNER_WORKSPACE}/idasdk75 env

    - name: Build
      working-directory: ${{ runner.workspace }}/
      shell: bash --login --norc -eo pipefail -o igncr '{0}'
      run: |
        make -C ${RUNNER_WORKSPACE}/idasdk75/plugins/loadmap
